/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projekt_BE;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        SchereSteinPapier schereSteinPapier = new SchereSteinPapier();

        Scanner scanner = new Scanner(System.in);

        System.out.println(schereSteinPapier.compareDecisions(scanner.next(),schereSteinPapier.playerTwo()));

    }
}
