/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Projekt_BE;

import Projekt_BE.web.WebServer;
import Projekt_BE.GameList.GameManager;

import java.util.Scanner;

public class Main {


    public static void main(String[] args) throws Exception {
        SchereSteinPapier schereSteinPapier = new SchereSteinPapier();
        GameManager gameManager = new GameManager();

        new WebServer(schereSteinPapier, gameManager).startServer();

        //Scanner scanner = new Scanner(System.in);

        //System.out.println(schereSteinPapier.compareDecisions(scanner.next(),schereSteinPapier.playerTwo()));

    }
}
